substitutions:
  name: localdeck
  friendly_name: LocalDeck MQTT

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
    sdkconfig_options: {}

logger:

ota:
  - platform: esphome
    password: !secret ota_password

api: {}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${friendly_name}

captive_portal:

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  log_topic: null

light:
  - platform: esp32_rmt_led_strip
    name: Ledstrip
    id: ledstrip
    rgb_order: GRB
    pin: GPIO8
    rmt_channel: 0
    num_leds: 24
    chipset: SK6812
    restore_mode: RESTORE_AND_OFF
    effects: []

  - platform: partition
    id: keypad_button_01_light
    name: Button 01 Light
    internal: false
    segments:
      - id: ledstrip
        from: 0
        to: 0
    # ... repeat

matrix_keypad:
  id: keypad
  keys: ABCDEFGHIJKLMNOPQRSTUVWX
  rows:
    - pin:
        number: GPIO21
        allow_other_uses: true
    - pin:
        number: GPIO20
        allow_other_uses: true
    - pin:
        number: GPIO3
        allow_other_uses: true
    - pin:
        number: GPIO7
        allow_other_uses: true
  columns:
    - pin: GPIO0
    - pin: GPIO1
    - pin: GPIO10
    - pin: GPIO4
    - pin: GPIO5
    - pin: GPIO6

binary_sensor:
  - platform: gpio
    id: keypad_row_21
    pin:
      number: GPIO21
      allow_other_uses: true
  - platform: gpio
    id: keypad_row_20
    pin:
      number: GPIO20
      allow_other_uses: true
  - platform: gpio
    id: keypad_row_03
    pin:
      number: GPIO3
      allow_other_uses: true
  - platform: gpio
    id: keypad_row_07
    pin:
      number: GPIO7
      allow_other_uses: true

  - platform: matrix_keypad
    id: keypad_button_01
    name: Button 01
    internal: false
    keypad_id: keypad
    key: A # (...B, C, D etc)
    on_press: []
    on_click: []
    on_double_click: []
    on_multi_click: []
